backend:
  name: github
  repo: OberhuemerBooks/oberhuemerbooks.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth
  site_domain: https://oberhuemer-books.org


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Text", name: "body", widget: "markdown" }
