backend:
  name: github
  repo: OberhuemerBooks/oberhuemerbooks.github.io
  branch: main
  base_url: https://6a32cd7471656d1db0a4067e--candid-starlight-d89419.netlify.app/
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Text", name: "body", widget: "markdown" }
